apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: app-login
  name: deployment-login
  namespace: login
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: app-login
  minReadySeconds: 60
  strategy:
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 1
    type: RollingUpdate      
  template:
    metadata:
      labels:
        app: app-login
    spec:
      containers:
        - name: app-login
          image: 857378965163.dkr.ecr.us-east-1.amazonaws.com/spv_login/login:latest
          ports:
            - containerPort: 8000
          envFrom:
            - configMapRef:
                name: configmap-login
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            periodSeconds: 30
            timeoutSeconds: 15
            failureThreshold: 3
            initialDelaySeconds: 60
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            periodSeconds: 30
            timeoutSeconds: 15
            failureThreshold: 5
            initialDelaySeconds: 30
          resources:
            requests:
              cpu: 100m
              memory: 300Mi
            limits:
              cpu: 200m
              memory: 512Mi
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      securityContext: {}
      terminationGracePeriodSeconds: 30

