apiVersion: v1
kind: Service
metadata:
  name: service-login
  namespace: video-system
  labels:
    app: app-login
spec:
  ports:
  - name: service-login-http
    port: 8000
    protocol: TCP
    targetPort: 8000
  selector:
    app: app-login
  type: LoadBalancer
